version: '3'

services:
  wppconnect:
    build:
      context: .
    volumes:
      - ./config:/usr/src/wpp-server/config
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - '21465:21465'

volumes:
  wppconnect_tokens: {}
